In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

In [3]:
df=pd.read_csv("diabetes (4).csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [5]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [6]:
268/500

0.536

In [7]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [8]:
X = df.drop('Outcome',axis=1)
y=df['Outcome']

In [23]:
from sklearn.preprocessing import MinMaxScaler
ms=MinMaxScaler()
X_scaled=ms.fit_transform(X)
X_scaled[:2]

array([[0.35294118, 0.74371859, 0.59016393, 0.35353535, 0.        ,
        0.50074516, 0.23441503, 0.48333333],
       [0.05882353, 0.42713568, 0.54098361, 0.29292929, 0.        ,
        0.39642325, 0.11656704, 0.16666667]])

In [30]:
X_scaled=pd.DataFrame(X_scaled,columns=X.columns)
X_scaled

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,0.352941,0.743719,0.590164,0.353535,0.000000,0.500745,0.234415,0.483333
1,0.058824,0.427136,0.540984,0.292929,0.000000,0.396423,0.116567,0.166667
2,0.470588,0.919598,0.524590,0.000000,0.000000,0.347243,0.253629,0.183333
3,0.058824,0.447236,0.540984,0.232323,0.111111,0.418778,0.038002,0.000000
4,0.000000,0.688442,0.327869,0.353535,0.198582,0.642325,0.943638,0.200000
...,...,...,...,...,...,...,...,...
763,0.588235,0.507538,0.622951,0.484848,0.212766,0.490313,0.039710,0.700000
764,0.117647,0.613065,0.573770,0.272727,0.000000,0.548435,0.111870,0.100000
765,0.294118,0.608040,0.590164,0.232323,0.132388,0.390462,0.071307,0.150000
766,0.058824,0.633166,0.491803,0.000000,0.000000,0.448584,0.115713,0.433333
767,0.058824,0.467337,0.573770,0.313131,0.000000,0.453055,0.101196,0.033333

In [9]:
X.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

In [10]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y)

In [11]:
x_train.head(3)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
597,1,89,24,19,25,27.8,0.559,21
249,1,111,86,19,0,30.1,0.143,23
239,0,104,76,0,0,18.4,0.582,27

In [12]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y,random_state=42)

In [33]:
x_train.head(3)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
353,1,90,62,12,43,27.2,0.580,24
711,5,126,78,27,22,29.6,0.439,40
373,2,105,58,40,94,34.9,0.225,25

In [34]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [35]:
X.shape,x_train.shape,x_test.shape

((768, 8), (614, 8), (154, 8))

In [36]:
y_train.head(3)

353    0
711    0
373    0
Name: Outcome, dtype: int64

In [37]:
y.shape,y_train.shape,y_test.shape

((768,), (614,), (154,))

In [38]:
X_scaled_df=pd.DataFrame(X_scaled,columns=X.columns)
X_scaled_df.head(3)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,0.352941,0.743719,0.590164,0.353535,0.0,0.500745,0.234415,0.483333
1,0.058824,0.427136,0.540984,0.292929,0.0,0.396423,0.116567,0.166667
2,0.470588,0.919598,0.524590,0.000000,0.0,0.347243,0.253629,0.183333

In [39]:
x_train,x_test,y_train,y_test=train_test_split(X_scaled,y,test_size=0.2,stratify=y)

In [40]:
x_train.head(3)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
402,0.294118,0.683417,0.688525,0.414141,0.104019,0.521610,0.088813,0.233333
729,0.117647,0.462312,0.426230,0.000000,0.000000,0.448584,0.026900,0.016667
153,0.058824,0.768844,0.672131,0.424242,0.573286,0.605067,0.260034,0.033333

In [43]:
from sklearn.tree import DecisionTreeClassifier
scores=cross_val_score(DecisionTreeClassifier(),X,y,cv=5)
scores

array([0.68831169, 0.68181818, 0.66233766, 0.78431373, 0.73202614])

In [45]:
from sklearn.tree import DecisionTreeClassifier
scores=cross_val_score(DecisionTreeClassifier(),X,y,cv=5)
print(type(scores))
print("Five accuracies on different splits:",scores)
print("Final accuracy(mean):",scores.mean())

<class 'numpy.ndarray'>
Five accuracies on different splits: [0.69480519 0.68181818 0.68181818 0.81045752 0.75163399]
Final accuracy(mean): 0.7241066123419063

In [49]:
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [50]:
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)
y_pred

array([1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1])

In [52]:
from sklearn.metrics import accuracy_score
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)
y_pred
acc=accuracy_score(y_test,y_pred)
print("Accuracy:",acc)

Accuracy: 0.6883116883116883

In [53]:
dt.score(x_test,y_test)

0.6883116883116883

In [59]:
from sklearn.ensemble import BaggingClassifier
from sklearn.linear_model import LogisticRegression
bag_cls=BaggingClassifier(
     estimator=LogisticRegression(),
     n_estimators=100,
     max_samples=0.8,
     oob_score=True,
     random_state=42
)
bag_cls.fit(x_train,y_train)
print("Accuracy of bagging(LG):",bag_cls.score(x_test,y_test))

Accuracy of bagging(LG): 0.7467532467532467

In [61]:
from sklearn.ensemble import BaggingClassifier
from sklearn.linear_model import LogisticRegression
bag_cls=BaggingClassifier(
     estimator=DecisionTreeClassifier(),
     n_estimators=100,
     max_samples=0.8,
     oob_score=True,
     random_state=42
)
bag_cls.fit(x_train,y_train)
print("Accuracy of bagging(DT):",bag_cls.score(x_test,y_test))

Accuracy of bagging(DT): 0.7402597402597403

In [62]:
from sklearn.metrics import accuracy_score
Lr=LogisticRegression()
Lr.fit(x_train,y_train)
y_pred=Lr.predict(x_test)
y_pred
acc=accuracy_score(y_test,y_pred)
print("Accuracy:",acc)

Accuracy: 0.7532467532467533

HEART DATASET

In [3]:
import pandas as pd
df=pd.read_csv("heart (2).csv")
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [4]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [5]:
df['HeartDisease'].value_counts()

HeartDisease
1    508
0    410
Name: count, dtype: int64

In [7]:
410/508

0.8070866141732284

In [8]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [10]:
df.shape

(918, 12)

In [11]:
X = df.drop('HeartDisease',axis=1)
y=df['HeartDisease']

In [14]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
X=X.select_dtypes(include=['int64','float64'])
ms=MinMaxScaler()
X_scaled=ms.fit_transform(X)
print(X_scaled[:2])

[[0.24489796 0.7        0.47927032 0.         0.78873239 0.29545455]
 [0.42857143 0.8        0.29850746 0.         0.67605634 0.40909091]]

In [15]:
X_scaled=pd.DataFrame(X_scaled,columns=X.columns)
X_scaled

          Age  RestingBP  Cholesterol  FastingBS     MaxHR   Oldpeak
0    0.244898       0.70     0.479270        0.0  0.788732  0.295455
1    0.428571       0.80     0.298507        0.0  0.676056  0.409091
2    0.183673       0.65     0.469320        0.0  0.267606  0.295455
3    0.408163       0.69     0.354892        0.0  0.338028  0.465909
4    0.530612       0.75     0.323383        0.0  0.436620  0.295455
..        ...        ...          ...        ...       ...       ...
913  0.346939       0.55     0.437811        0.0  0.507042  0.431818
914  0.816327       0.72     0.320066        1.0  0.570423  0.681818
915  0.591837       0.65     0.217247        0.0  0.387324  0.431818
916  0.591837       0.65     0.391376        0.0  0.802817  0.295455
917  0.204082       0.69     0.290216        0.0  0.795775  0.295455

[918 rows x 6 columns]

In [18]:
X.head()

   Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak
0   40        140          289          0    172      0.0
1   49        160          180          0    156      1.0
2   37        130          283          0     98      0.0
3   48        138          214          0    108      1.5
4   54        150          195          0    122      0.0

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y)

In [23]:
X_train.head(3)

     Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak
831   63        135          252          0    172      0.0
326   45        110            0          0    138     -0.1
837   57        150          168          0    174      1.6

In [24]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y,random_state=42)

In [25]:
x_train.head(3)

     Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak
485   63        139          217          1    128      1.2
486   55        110          214          1    180      0.4
117   59        130          338          1    130      1.5

In [26]:
df['HeartDisease'].value_counts()

HeartDisease
1    508
0    410
Name: count, dtype: int64

In [27]:
X.shape,x_train.shape,x_test.shape

((918, 6), (734, 6), (184, 6))

In [28]:
y_train.head(3)

485    1
486    0
117    1
Name: HeartDisease, dtype: int64

In [29]:
y.shape,y_train.shape,y_test.shape

((918,), (734,), (184,))

In [30]:
X_scaled_df=pd.DataFrame(X_scaled,columns=X.columns)
X_scaled_df.head(3)

        Age  RestingBP  Cholesterol  FastingBS     MaxHR   Oldpeak
0  0.244898       0.70     0.479270        0.0  0.788732  0.295455
1  0.428571       0.80     0.298507        0.0  0.676056  0.409091
2  0.183673       0.65     0.469320        0.0  0.267606  0.295455

In [31]:
x_train,x_test,y_train,y_test=train_test_split(X_scaled,y,test_size=0.2,stratify=y)

In [32]:
x_train.head(3)

          Age  RestingBP  Cholesterol  FastingBS     MaxHR   Oldpeak
373  0.632653      0.675     0.000000        0.0  0.387324  0.409091
447  1.000000      0.620     0.283582        0.0  0.352113  0.522727
322  0.204082      0.525     0.000000        1.0  0.746479  0.613636

In [34]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
scores=cross_val_score(DecisionTreeClassifier(),X,y,cv=5)
scores

array([0.68478261, 0.58152174, 0.72282609, 0.65027322, 0.62295082])

In [35]:
from sklearn.tree import DecisionTreeClassifier
scores=cross_val_score(DecisionTreeClassifier(),X,y,cv=5)
print(type(scores))
print("Five accuracies on different splits:",scores)
print("Final accuracy(mean):",scores.mean())

<class 'numpy.ndarray'>
Five accuracies on different splits: [0.66304348 0.59782609 0.70108696 0.67759563 0.6010929 ]
Final accuracy(mean): 0.6481290092658588

In [36]:
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [37]:
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)
y_pred

array([0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1])

In [38]:
from sklearn.metrics import accuracy_score
dt=DecisionTreeClassifier()
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)
y_pred
acc=accuracy_score(y_test,y_pred)
print("Accuracy:",acc)

Accuracy: 0.6793478260869565

In [39]:
dt.score(x_test,y_test)

0.6793478260869565

In [42]:
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
Lr=LogisticRegression()
Lr.fit(x_train,y_train)
y_pred=Lr.predict(x_test)
y_pred
acc=accuracy_score(y_test,y_pred)
print("Accuracy:",acc)

Accuracy: 0.7554347826086957